/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package polynomial;

public class App {
    public static void main(String[] args) {
        Polynomial p = new Polynomial(new int[] {1290, 1, 2, 5, 3});
        System.out.println(p.differentiate(15).toString());
    }
}
